Yevhenii/ibc precompile
Kava-Labs/go-ethereum pull request #14
Opened 2024-02-21 18:58 UTC by evgeniy-scherbina

2024-02-22 22:38 UTC, nddeluca commented on accounts/abi/abi.go
> +func (abi ABI) getInputs(name string, data []byte, useStrictMode bool) (Arguments, error) {
These don't depend on non-private methods or data -- let's not extend the abi type and use composition or create helpers in the kava repo

2024-02-22 22:39 UTC, nddeluca commented on core/vm/interface.go
> +	IBCTransfer(goCtx context.Context, msg *contract.MsgTransfer) (*contract.MsgTransferResponse, error)
See #15, lets use a type assertion route and avoid modifying these core types

2024-02-22 22:40 UTC, nddeluca requested changes
Good spike but let's avoid extending core types & code.  This is a bit coupled to cosmos/kava and causes quite a bit of duplication.

2024-02-23 21:53 UTC, evgeniy-scherbina commented on accounts/abi/abi.go
> +func (abi ABI) getInputs(name string, data []byte, useStrictMode bool) (Arguments, error) {
We agreed to left code as it is, doc comments were added here: 1da08d0345d3ad0f24116b0bda0ee9c1c932f33d

2024-02-24 16:27 UTC, nddeluca commented on accounts/abi/abi.go
> +func (abi ABI) getInputs(name string, data []byte, useStrictMode bool) (Arguments, error) {
Thnx for adding comments -- see the symmetry now and that extending the type is a better path

2024-02-26 14:55 UTC, evgeniy-scherbina commented on core/vm/interface.go
> +	IBCTransfer(goCtx context.Context, msg *contract.MsgTransfer) (*contract.MsgTransferResponse, error)
Fixed here: a66d490d3d3b061c91bbe90772e3a1c10e60a9f8

Related changes:
- ethermint: https://github.com/Kava-Labs/ethermint/pull/37/commits/638be0d0efe93866ce9d2e1a4c37262ab9cf7f93
- kava: https://github.com/Kava-Labs/kava/pull/1826/commits/11a2b8ed0f56124225839d9612abf07afe1e3a5f

2024-03-07 19:16 UTC, closed without merging